{
    "name": "HTPlus APS Core",
    "version": "18.0.1.5.0",
    "summary": "Demand planning, production planning, APS scheduling and simulation.",
    "author": "Ba.TD",
    "maintainer": "Ba.TD",
    "license": "LGPL-3",
    "category": "HTPlus",
    "depends": [
        "htplus_planning_base",
        "mail",
    ],
    "data": [
        "data/ir_sequence_data.xml",
        "security/ir.model.access.csv",
        "views/htplus_aps_menus.xml",
        "views/htplus_dashboard_views.xml",
        "views/htplus_shift_dashboard_views.xml",
        "views/htplus_demand_plan_views.xml",
        "views/htplus_demand_import_views.xml",
        "views/htplus_production_plan_views.xml",
        "views/htplus_schedule_views.xml",
        "views/htplus_simulation_views.xml",
        "views/htplus_workforce_views.xml",
        "views/htplus_settings_views.xml",
        "reports/htplus_schedule_report.xml",
        "reports/htplus_schedule_report_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "htplus_aps_core/static/src/gantt/htplus_gantt_actions.js",
            "htplus_aps_core/static/src/gantt/htplus_gantt_actions.xml",
            "htplus_aps_core/static/src/gantt/htplus_gantt.js",
            "htplus_aps_core/static/src/gantt/htplus_gantt.xml",
            "htplus_aps_core/static/src/gantt/htplus_gantt.scss",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
